
version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_d
    ports:
      - "5173:5173"
  backend:
    build: ./backend
    container_name: backend_d
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true